#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh

cp system/cRefine.topoSetDict1 system/topoSetDict

topoSet

refineMesh -overwrite -dict system/refineMeshDict

cp system/cRefine.topoSetDict2 system/topoSetDict

topoSet

refineMesh -overwrite -dict system/refineMeshDict

#cp system/cRefine.topoSetDict3 system/topoSetDict

#topoSet

#refineMesh -overwrite -dict system/refineMeshDict

#cp system/cRefine.topoSetDict4 system/topoSetDict

#topoSet

#refineMesh -overwrite -dict system/refineMeshDict
